# included segment of Makefile to add $OPENCV_INC and $OPENCV_LIB flags

OPENCV_INC = -I/usr/include/opencv4
OPENCV_LIB = -L/usr/local/lib -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core

OPENCV=$(OPENCV_INC) $(OPENCV_LIB)

